# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 12:43
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_allow_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_preview',
            field=tinymce.models.HTMLField(),
        ),
    ]
