# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 15:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170607_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_preview',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
