# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170607_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(default='', max_length=200, verbose_name='Описание статьи для поисковика'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_kayword',
            field=models.CharField(default='', max_length=200, verbose_name='Ключевые слова'),
        ),
    ]
