# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170607_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
